### ISSUE TITLE
config for the keeper block not working

### ISSUE THREAD

**Issue by mattrix444** [resinate/PlayerStorage#1]
i have the config set to true for the keeper block but when i die i still have the stuff in my inventory anyway. thanks

**Comment by resinate** [comment]
in next update, i disabled all blocks. im not pro at coding but using it personal storage works fine.
but yea no keeper block or interface, for now.

**Comment by resinate** [comment]
you need to delete playerstorage.cfg and let game auto gen a new one and make changes u want.
